export default [
  {
    id: 9,
    name: 'Россия',
    cities: [
      { id: 28, name: 'Тверь', country: 9 },
      { id: 29, name: 'Рязань', country: 9 },
      { id: 30, name: 'Самара', country: 9 },
      { id: 31, name: 'Тольятти', country: 9 },
      { id: 32, name: 'Ижевск', country: 9 },
      { id: 33, name: 'Саратов', country: 9 },
      { id: 34, name: 'Санкт-Петербург', country: 9 },
      { id: 35, name: 'Москва', country: 9 },
      { id: 36, name: 'Сергиев Посад', country: 9 },
      { id: 201, name: 'Нижний Новгород', country: 9 },
      { id: 202, name: 'Волгоград', country: 9 },
      { id: 411, name: 'Брянск', country: 9 },
      { id: 472, name: 'Краснодар', country: 9 },
      { id: 496, name: 'Муром', country: 9 },
      { id: 577, name: 'Тула', country: 9 },
      { id: 586, name: 'Владимир', country: 9 },
      { id: 591, name: 'Воронеж', country: 9 },
      { id: 597, name: 'Екатеринбург', country: 9 },
    ],
  },
  {
    id: 35,
    name: 'Индия',
    cities: [
      { id: 238, name: 'Хайдарабад', country: 35 },
      { id: 239, name: 'Пуна', country: 35 },
      { id: 734, name: 'Гургаон', country: 35 },
      { id: 735, name: 'Ченнаи', country: 35 },
      { id: 736, name: 'Бангалор', country: 35 },
    ],
  },
  { id: 63, name: 'Кыргызстан', cities: [{ id: 739, name: 'Бишкек', country: 63 }] },
  { id: 55, name: 'Узбекистан', cities: [{ id: 699, name: 'Ташкент', country: 55 }] },
  { id: 58, name: 'Литва', cities: [{ id: 704, name: 'Вильнюс', country: 58 }] },
  {
    id: 1,
    name: 'Украина',
    cities: [
      { id: 1, name: 'Харьков', country: 1 },
      { id: 2, name: 'Киев', country: 1 },
      { id: 3, name: 'Львов', country: 1 },
      { id: 4, name: 'Винница', country: 1 },
      { id: 5, name: 'Днепр', country: 1 },
      { id: 276, name: 'Ужгород', country: 1 },
      { id: 626, name: 'Черновцы', country: 1 },
      { id: 639, name: 'Ивано-Франковск', country: 1 },
      { id: 644, name: 'Хмельницкий', country: 1 },
      { id: 655, name: 'Луцк', country: 1 },
      { id: 675, name: 'Ровно', country: 1 },
      { id: 682, name: 'Тернополь', country: 1 },
    ],
  },
  {
    id: 10,
    name: 'Беларусь',
    cities: [
      { id: 37, name: 'Витебск', country: 10 },
      { id: 38, name: 'Брест', country: 10 },
      { id: 39, name: 'Могилев', country: 10 },
      { id: 40, name: 'Гомель', country: 10 },
      { id: 41, name: 'Гродно', country: 10 },
      { id: 42, name: 'Минск', country: 10 },
      { id: 50, name: 'Полоцк', country: 10 },
    ],
  },
  { id: 61, name: 'Испания', cities: [{ id: 725, name: 'Малага', country: 61 }] },
  {
    id: 4,
    name: 'Армения',
    cities: [
      { id: 9, name: 'Ереван', country: 4 },
      { id: 280, name: 'Гюмри', country: 4 },
      { id: 715, name: 'Горис', country: 4 },
    ],
  },
  {
    id: 62,
    name: 'Вьетнам',
    cities: [
      { id: 737, name: 'Ханой', country: 62 },
      { id: 738, name: 'Хошимин', country: 62 },
    ],
  },
  {
    id: 56,
    name: 'Польша',
    cities: [
      { id: 700, name: 'Краков', country: 56 },
      { id: 701, name: 'Гданьск', country: 56 },
    ],
  },
  { id: 59, name: 'Грузия', cities: [{ id: 705, name: 'Тбилиси', country: 59 }] },
  {
    id: 11,
    name: 'Казахстан',
    cities: [
      { id: 43, name: 'Нур-Султан', country: 11 },
      { id: 44, name: 'Караганда', country: 11 },
      { id: 203, name: 'Алматы', country: 11 },
    ],
  },
  { id: 57, name: 'Венгрия', cities: [{ id: 703, name: 'Будапешт', country: 57 }] },
];
